### PR TITLE
llvm: enable all default targets

### PR DESCRIPTION
**Pull request by jedahan**

### CODE REVIEW

**Comment by git-bruh** [comment]
see https://github.com/kiss-community/repo/issues/31﻿

**Comment by jedahan** [comment]
Hmm, regardless of the zig implications, as far as I understand the 100mb of increased disk space is not worth the ability for people to cross-compile without (knowing to look for) the zig repo and using that?

I'll respect the decision, even if I disagree with it due to:

* our packaged llvm being non-default, therefore non-kiss (already, 3 folks were surprised that zig didn't compile and had to spend time digging why)
* anyone concerned with 100mb of disk space will likely be uninstalling llvm and any other build-time deps
* more versions of llvm in kiss-repos / personal repositories unrelated to llvm (zig), more dissonance between installs

Feel free to close this issue if you still believe the current situation is better than using the default targets.

**Comment by ominitay** [comment]
Zig now can't be compiled since LLVM 12 / Zig 0.8. This change would prevent us from needing to drop Zig, and would allow Zig to cross-compile by default.

**Comment by kyx0r** [comment]
What if somehow in the zig build script (since its techically just a posix shell script) you write code that will force llvm to recompile with all default targets? That way you don't have to compromise the compile times of regular users who don't care about zig. In this solution you would not need to maintain a separate fork of llvm package, you just procedurally change the build script for llvm from the zig build script or whatever.

**Comment by kyx0r** [comment]
Reading though some of the threads apparently I wasn't the first to think about making some kind of dynamic package to sovle this problem. But yeah I agree with them saying its not exactly KISS favorable thing. However since its just one independent package that is installed only by user choice and does not really bring any extra baggage for it to work I would still make it, even if thats not going to get accepted into this repo, I keep it in my personal repo and not have to worry about maintaing forked llvm package.

**Comment by ominitay** [comment]
We shouldn't be modifying another package's build script from another package's build script. The way I see it is that either the LLVM package is changed to build with default targets enabled, which is the recommended and expected way to do things, or the Zig package is dropped.

**Comment by jedahan** [comment]
I hesitated mentioning zig in particular, since that is just an example use case. Even if zig compiled fine with the current llvm, I think its a good idea to enable default targets for anyone who wants to use llvm as end-user software, not just a build tool for the rest of their packages.

**Comment by ominitay** [comment]
> I hesitated mentioning zig in particular, since that is just an example use case. Even if zig compiled fine with the current llvm, I think its a good idea to enable default targets for anyone who wants to use llvm as end-user software, not just a build tool for the rest of their packages.

Sure, but the Zig incompatibility is a good example of the negative consequences of having a non-standard build of LLVM.

**Comment by sdsddsd1** [comment]
What if we leave the package as is and add a comment on how to enable all targets. So people who e.g want to build zig and start to troubleshoot will have an easier time figuring out and just fork llvm.

**Comment by ominitay** [comment]
Any package in the community repository should depend on packages only from the community repository and main repositories. It's not KISS to make users fork packages just to be able to build a package in the community repo. Besides, this issue goes beyond Zig.

We should end discussion re. the Zig package here, since it isn't really relevant to the issue topic either.

**Comment by dilyn-corner** [comment]
I'm interested in what our `llvm` build causes problems for outside of `zig`? 

That our build of `llvm` is "nonstandard" isn't terribly problematic to me -- a lot of our packages are 'nonstandard' depending on your metric, so that would be interesting to hear more on. 

I did say a lot about this last time, but I'll add something new for why I don't like this idea:
`llvm` is a run-time requirement for `rust` and `mesa` (by default in the latter case). Neither `rust` nor `mesa` require `llvm` to be built with all targets. `rust` is only around for `firefox` - if we had gone with any other browser, `rust` may very well not even be in the repository. But my real problem is with `mesa`. 

`mesa` is here as (a nondeprecated) graphics library provider. So as far as I'm concerned, almost every use-case will have `mesa`. An indeterminable number of users will be using Radeon graphics, and thus need `llvm` -- I'd go as far as to say that most people don't even bother modifying the `mesa` build to drop this requirement. Which means that (probably) most users have `llvm` on their systems. What would increasing this install size by 100MB+ get them? 

Probably basically nothing, unless they want `zig`, which only has this requirement because it DEMANDS that you be able to build a cross-compiler (which I think is an unreasonable request). 

I'm more than happy to make exceptions to things for use-cases that don't impact users in negative ways and provide something of benefit to someone. But KISS ostensibly only targets x86. Essentially, there isn't a salient benefit to having `llvm`, a package most people will have installed at all times, see a 30% size increase so that some users can build `zig` -- which doesn't actually have anything in any repository that requires it anyway. 

What I basically need is some sort of strong justification to encroach on the bytes on users' hard drives.

**Comment by illiliti** [comment]
> 30% size increase

and build time

(The fair way) I suggest to keep llvm as is until default targets will be required by something essential(rust, mesa, ...)
(The better way) I also suggest encouraging zig developers to allow building without default targets.

**Comment by jedahan** [comment]
> > 30% size increase
> 
> and build time
> 
> (The fair way) I suggest to keep llvm as is until default targets will be required by something essential(rust, mesa, ...)
> (The better way) I also suggest encouraging zig developers to allow building without default targets.

From previous threads, build time was within margin of error (was actually decreased)

**Comment by ominitay** [comment]
By my tests, compilation time decreased. Obviously, that is improbable, and a sample size of 1, but does show that it is likely a negligible difference.

Cross compilation is a key feature of Zig, so they are unlikely to make it optional, though do start an issue in the Zig repo if you have the time :)

I'd argue that easy cross compilation is certainly a price worth paying for 100MB of storage. If one is so concerned over such a small amount of storage, they probably won't be using LLVM.

Merging this will hugely benefit those who use Zig, giving them a more simple way to install Zig, and opens the door for packages which depend on Zig. Is the slight storage increase really going to affect anyone? 100MB is really very little today in terms of storage.

**Comment by dilyn-corner** [comment]
> they probably won't be using LLVM.

Except I just explained a good reason to assume most KISS users have `llvm` installed.


> I'd argue that easy cross compilation is certainly a price worth paying for 100MB of storage

I'm inclined to disagree

> Merging this will hugely benefit those who use Zig

Currently 3 people :) 

> Is the slight storage increase really going to affect anyone? 100MB is really very little today in terms of storage.

It's not a matter of how cheap storage is. The problem is that we'd be grossly increasing the size of a package for seemingly no benefit to any arbitrary user.

**Comment by jedahan** [comment]
@dilyn-corner There are tons of packages in kiss that have optional defaults that don't benefit every user. If enabling default behavior benefits some users, but doesn't hurt most users, why is there so much friction to help those who can benefit?

(One example is enabling icu support in nodejs - if people are using nodejs to run english-only software, that shouldn't stop anyone from being able to create software that supports other languages in kiss).

**Comment by konimex** [comment]
Before this discussion veers of further, I would remind all of you of the KISS guidestones, https://k1sslinux.org/guidestones.

Also, the inclusion of LLVM in the first place is because of Mesa and Firefox. Had AMDGPU devices not require LLVM at all, this PR probably wouldn't exist at all. If there was a browser apart of Firefox which is "simpler" (depends on the definitions) *but* doesn't sacrifice a lot of usability (again, different sites for different people, but we're talking about the usual sites eventhough <s>there's a lot of bullshit regarding "centralized" sites</s>some people would rather use alternatives), LLVM (and clang) probably wouldn't hit the main repo at all.

Regarding cross-compiling (and therefore, Zig), I don't know why Dilyn decides to drop this section at all, but KISS supports `x86_64` and only `x86_64` (https://github.com/kiss-community/wiki/blob/1350ff54a5ea7b0152a3d39627ef36241f56ffdf/community/ports.txt#L5) and, Dylan's not keen either on cross-compiling: https://freenode.logbot.info/kisslinux/20190910#c2637698

**Comment by dilyn-corner** [comment]
Note that I didn't drop statements about KISS only supporting English/64-bit, I only dropped the wiki page talking about ports. The project still only aims to support x86_64. 

I feel like I've made very clear what the cause of the friction is and why this change doesn't have enough value to merit inclusion. Pushing aside my problems with cross-compiling, I still don't see a good answer to my previous statement: 

> What I basically need is some sort of strong justification to encroach on the bytes on users' hard drives.

If the *only* good reason is that it allows users to "more easily" have access to `zig`, I'm not sold -- `zig` advertises itself as a simple way to cross-compile (among other things), and KISS simply isn't concerned with this. 

I don't see the value, and nobody has demonstrated it.

Fundamentally, it's not that this adds "negligible amounts of space". It's that it does so for no actually good reason to do so.

**Comment by ominitay** [comment]
> Regarding cross-compiling (and therefore, Zig), I don't know why Dilyn decides to drop this section at all, but KISS supports `x86_64` and only `x86_64` (https://github.com/kiss-community/wiki/blob/1350ff54a5ea7b0152a3d39627ef36241f56ffdf/community/ports.txt#L5) 

KISS only supports `x86_64`, yes. But that doesn't mean it can't or shouldn't support tools which can be used to cross compile. It is strictly in terms of the package manager.

> Dylan's not keen either on cross-compiling: https://freenode.logbot.info/kisslinux/20190910#c2637698

That's taken out of context. He is discussing the KISS package manager, not cross compilation in general.

**Comment by jedahan** [comment]
If llvm only exists for firefox and mesa, why is it even an end-user installable package at all? Why not put it in the build scripts of firefox (like we do for autoconf and yasm) and mesa and then it can be as minimal as needed?

That way it wouldn't be surprising when someone does `kiss build llvm` and cannot target anything but the machine its being run on, in any language (rust, zig, c, etc...).

I think the biggest difference in perspective comes from people who want to use llvm as a end-user, vs people who see llvm as a necessary dependency of the rest of their system.

**Comment by jedahan** [comment]
> Note that I didn't drop statements about KISS only supporting English/64-bit, I only dropped the wiki page talking about ports. The project still only aims to support x86_64.
> 
> I feel like I've made very clear what the cause of the friction is and why this change doesn't have enough value to merit inclusion. Pushing aside my problems with cross-compiling, I still don't see a good answer to my previous statement:
> 
> > What I basically need is some sort of strong justification to encroach on the bytes on users' hard drives.
> 
> If the _only_ good reason is that it allows users to "more easily" have access to `zig`, *snip*

It allows cross compilation for rust, c, and more. Its not just zig.

> *snip* I'm not sold -- `zig` advertises itself as a simple way to cross-compile (among other things), and KISS simply isn't concerned with this.
> 

KISS isn't concerned with cross-compilation for your own system, but if a user wants to build software for multiple platforms, that use case should be supported. Just like the kiss system only supports english, but doesn't prevent users  from writing software that supports other languages.

> I don't see the value, and nobody has demonstrated it.
> 

The value is being able to compile for architectures you are not currently running - its very useful for having a powerful computer compile for a less powerful one, like a raspberry pi. If it wasn't a valuable feature, not only would llvm not have it, but it wouldn't be enabled by default.

> Fundamentally, it's not that this adds "negligible amounts of space". It's that it does so for no actually good reason to do so.

So far I have not seen anyone demonstrate the harm of using "negligible amounts of space". Especially since someone who is concerned with space will likely remove build-time dependencies (yes llvm is runtime dep of rust, but rust is only a build-time dep of firefox. so both can be removed after build.)

**Comment by dilyn-corner** [comment]
> but if a user wants to build software for multiple platforms, that use case should be supported

Why?

> Just like the kiss system only supports english, but doesn't prevent users from writing software that supports other languages.

KISS doesn't prevent people from cross-compiling software. `kiss` easily and painlessly allows modifying packages to enable or disable features not normally included. 

 
> The value is being able to compile for architectures you are not currently running - its very useful for having a powerful computer compile for a less powerful one, like a raspberry pi. If it wasn't a valuable feature, not only would llvm not have it, but it wouldn't be enabled by default.

Right, but it isn't valuable *to KISS*. Why support a cross-compiler when KISS isn't setup for it? 
`gcc` doesn't do it. Should we enable multilib support with `gcc`? Should we add flags to build files so that users can specify host and target? No, because we aim at x86_64. If being able to cross-compile is useful for a user, then they can make that choice. But I'm going to make what is probably a very safe assertion: almost nobody using KISS cares about cross-compiling. So there isn't a benefit to most users in doing this, so why can't the minority leverage the tools already available to easily solve this problem?

> So far I have not seen anyone demonstrate the harm of using "negligible amounts of space". 

Because that additional space provides zero value. `git` is absolutely massive. Why is that okay? Because having a static `git` is more useful than not having 27MB of free space. A static `git` (read: a larger `git`) provides actual value to users. 

> Especially since someone who is concerned with space will likely remove build-time dependencies (yes llvm is runtime dep of rust, but rust is only a build-time dep of firefox. so both can be removed after build.)

...Except that it's also a run-time dependency for `mesa`, so I'll just quote myself:
> mesa is here as (a nondeprecated) graphics library provider. So as far as I'm concerned, almost every use-case will have mesa. An indeterminable number of users will be using Radeon graphics, and thus need llvm -- I'd go as far as to say that most people don't even bother modifying the mesa build to drop this requirement. Which means that (probably) most users have llvm on their systems. What would increasing this install size by 100MB+ get them?
> Probably basically nothing

**Comment by jedahan** [comment]
First of all I want to say thank you @dilyn-corner for having the patience to continue to address the problem, defend and represent those you believe would benefit from the decision, and maintaining kiss. I feel like we are talking in circles, and clearly have difficulty in understanding each other's point-of-view, so I'll make one last attempt to explain myself, and close this PR regardless of the outcome you decide on after reading.

---

> > but if a user wants to build software for multiple platforms, that use case should be supported
> 
> Why?
> 

For the same reason we include any software in the distribution whatsoever - because people are interested in the use case.

> > Just like the kiss system only supports english, but doesn't prevent users from writing software that supports other languages.
> 
> KISS doesn't prevent people from cross-compiling software. `kiss` easily and painlessly allows modifying packages to enable or disable features not normally included.
> 

While I appreciate that forking individual packages is quick, it is not painless. One simple example: lots of repositories contain more than one package, and KISS_PATH is the only way I know to determine priority of package installs. So it often is the case where one package from one repo is resolved (often as a downgrade) because I am interested in another package only. 

I am not saying this is the fault of KISS, but if we are talking about keeping things simple, having to fork just one package from one repo and then maintain it is certainly more work than not having to do it.

In other words - there is a non-zero amount of work for people interesting in cross compiling. There is a zero amount of work involved in people who are not interested in cross compiling feature. I am asking to think of user needs as more valuable than computer needs - does this make sense?

> > The value is being able to compile for architectures you are not currently running - its very useful for having a powerful computer compile for a less powerful one, like a raspberry pi. If it wasn't a valuable feature, not only would llvm not have it, but it wouldn't be enabled by default.
> 
> Right, but it isn't valuable _to KISS_. 

It is at least valuable to the three people who chimed in to this thread.

> Why support a cross-compiler when KISS isn't setup for it?

Again, this is a mismatch of 'llvm as a build requirement for kiss, vs llvm as software to install and use'. I am not suggesting that KISS the system support cross compiling itself, I am suggesting that llvm the end-user package support the default features upstream.

> `gcc` doesn't do it. Should we enable multilib support with `gcc`? Should we add flags to build files so that users can specify host and target? No, because we aim at x86_64.

And again, I am not asking for KISS to target anything other than x86_64.

> If being able to cross-compile is useful for a user, then they can make that choice. But I'm going to make what is probably a very safe assertion: almost nobody using KISS cares about cross-compiling. So there isn't a benefit to most users in doing this, so why can't the minority leverage the tools already available to easily solve this problem?
> 

I am not able to comment on the safety of that assertion, only what I see here: three people asking for a feature that is normally in the upstream distribution, and two people saying they personally wouldn't use it, and claiming most people wouldn't.

> > So far I have not seen anyone demonstrate the harm of using "negligible amounts of space".
> 
> Because that additional space provides zero value. `git` is absolutely massive. Why is that okay? Because having a static `git` is more useful than not having 27MB of free space. A static `git` (read: a larger `git`) provides actual value to users.
> 

Agreed that static git is preferable in most cases.

> > Especially since someone who is concerned with space will likely remove build-time dependencies (yes llvm is runtime dep of rust, but rust is only a build-time dep of firefox. so both can be removed after build.)
> 
> ...Except that it's also a run-time dependency for `mesa`, so I'll just quote myself:
> 

Good point, this would affect anyone using mesa as well. I'd be happy to look at exactly how llvm is used in mesa runtime to see if this is strictly necessary, as it is a bit surprising for anything beyond the llvmpipe software rasterizer. (Which we probably want to support anyway).

> > mesa is here as (a nondeprecated) graphics library provider. So as far as I'm concerned, almost every use-case will have mesa. An indeterminable number of users will be using Radeon graphics, and thus need llvm -- I'd go as far as to say that most people don't even bother modifying the mesa build to drop this requirement. Which means that (probably) most users have llvm on their systems. What would increasing this install size by 100MB+ get them?
> > Probably basically nothing

I am not asking what users **get** for 100mb, I am asking how it negatively impacts users by having it enabled.

---

I also don't want to shut down any exploration about options to make this less painful. So far I've tried to come up with a few. If the more off-topic ideas are things people are interested in, we should split them off to issues/emails/other topics than this PR, trying to keep it focused on the thing at hand.

- enabling default targets
  - seems that if it provides no value to some users, that is more important than that it provides value to other users. this is something fundamentally confusing to me but keeping it here for completeness.

- llvm as a build-time only dependency for rust/firefox in the main repository
  - would still affect mesa but for those not using mesa, would not increase the size of their installed files

- update the build script to allow a user to `export LLVM_TARGETS_TO_BUILD="defaults"` or whatever the equivalent is needed, and maybe mention it in the `post-install`.
  - seems kind of hacky

- less minimal/more default llvm in the community repo
  - first proposal here, what if we had the 'end-user' package of llvm in the community extra repo. this would keep the default kiss distribution as minimal as it is today (and perhaps pave way to make it even more minimal), while still meeting user and upstream expectations

- some sort of improved support for dependency resolution that doesn't rely on every person having to fork and maintain individual packages? or maybe just some guidelines like "hey if you make a repository try and not bundle unrelated packages, like llvm and zig"? I dunno, this is least fully-formed.

**Comment by ominitay** [comment]
So doing a diff on the manifests for the two LLVM builds, the only difference is that the 'default' one has many more `/usr/lib/libLLVM[ARCH]*.a` files. Surely there is a way to build only those files, and to have a package which can add these?

Having a way to just add the additional targets with a separate package would give us the best of both worlds, so is certainly worth looking into! So there are still changes to the libLLVM-12.so files, I guess there's no way to do so then.

If only there was a `provides` and `conflicts` dependency system, whereby we could have an `llvm-min` a fully-featured `llvm` package.

**Comment by kyx0r** [comment]
> I'd go as far as to say that most people don't even bother modifying the mesa build to drop this requirement.

This actually inspired me to take a look at the mesa build, after hand tuning the build options only for my hardware (Radeon graphics on my prod pc) the package dropped about 350MB in size. Which is pretty masive, so if you care about this I suggest you to try it. Luckly the build is easy to modify through meson flags, so didn't even have to read though the mesa source code.

**Pull request closed without merging**
