### PR TITLE
mandoc: fix failing build

### PR DESCRIPTION
**Pull request by ominitay**

### CODE REVIEW

**Comment by git-bruh** [comment]
Build works fine here, could you share your build log ?

**Comment by ominitay** [comment]
Before fix: 
```
-> mandoc Starting build
patching file main.c
file config.log: writing...
file configure.local: reading...
tested operating system: Linux -> OSENUM=MANDOC_OS_OTHER
tested cc -W: tested noop: yes
selected CFLAGS="-O3 -pipe -march=native"
tested noop-static: yes
selected STATIC="-static"
tested dirent-namlen: no
tested be32toh: yes
tested be32toh-DSYS_ENDIAN: no
tested EFTYPE: no
tested err: yes
tested getline: yes
tested getsubopt: yes
tested isblank: yes
tested mkdtemp: yes
tested ntohl: yes
tested O_DIRECTORY: yes
tested PATH_MAX: yes
tested pledge: no
tested sandbox_init: no
tested progname: no
tested reallocarray: yes
tested recallocarray-D_OPENBSD_SOURCE: no
tested rewb-bsd: no
tested rewb-sysv: yes
tested strcasestr-D_GNU_SOURCE: yes
tested stringlist: no
tested strlcat: yes
tested strlcpy: yes
tested strndup: yes
tested strptime: yes
tested strsep: yes
tested strtonum-D_OPENBSD_SOURCE: no
tested vasprintf: yes
tested fts-DFTS_COMPARE_CONST: no
tested fts: no
tested less -T: no
./configure: line 1: locale: not found
./configure: line 1: locale: not found
tested wchar: no (no UTF8_LOCALE)
tested nanosleep: yes
tested ohash-lutil: no
selected LDADD="    -lz"
file config.h: written
file Makefile.local: written
Makefile:601: warning: ignoring prerequisites on suffix rule definition
Makefile:601: warning: ignoring prerequisites on suffix rule definition
Makefile:601: warning: ignoring prerequisites on suffix rule definition
Makefile:601: warning: ignoring prerequisites on suffix rule definition
Makefile:601: warning: ignoring prerequisites on suffix rule definition
cc -O3 -pipe -march=native   -c -o eqn_html.o eqn_html.c
cc -O3 -pipe -march=native   -c -o html.o html.c
cc -O3 -pipe -march=native   -c -o man_html.o man_html.c
cc -O3 -pipe -march=native   -c -o mdoc_html.o mdoc_html.c
cc -O3 -pipe -march=native   -c -o roff_html.o roff_html.c
cc -O3 -pipe -march=native   -c -o tbl_html.o tbl_html.c
cc -O3 -pipe -march=native   -c -o eqn_term.o eqn_term.c
cc -O3 -pipe -march=native   -c -o man_term.o man_term.c
cc -O3 -pipe -march=native   -c -o mdoc_term.o mdoc_term.c
cc -O3 -pipe -march=native   -c -o roff_term.o roff_term.c
cc -O3 -pipe -march=native   -c -o term.o term.c
cc -O3 -pipe -march=native   -c -o term_ascii.o term_ascii.c
cc -O3 -pipe -march=native   -c -o term_ps.o term_ps.c
cc -O3 -pipe -march=native   -c -o term_tab.o term_tab.c
cc -O3 -pipe -march=native   -c -o tbl_term.o tbl_term.c
cc -O3 -pipe -march=native   -c -o dbm.o dbm.c
cc -O3 -pipe -march=native   -c -o dbm_map.o dbm_map.c
cc -O3 -pipe -march=native   -c -o mansearch.o mansearch.c
cc -O3 -pipe -march=native   -c -o dba.o dba.c
cc -O3 -pipe -march=native   -c -o dba_array.o dba_array.c
cc -O3 -pipe -march=native   -c -o dba_read.o dba_read.c
cc -O3 -pipe -march=native   -c -o dba_write.o dba_write.c
cc -O3 -pipe -march=native   -c -o mandocdb.o mandocdb.c
cc -O3 -pipe -march=native   -c -o main.o main.c
cc -O3 -pipe -march=native   -c -o manpath.o manpath.c
cc -O3 -pipe -march=native   -c -o mdoc_man.o mdoc_man.c
cc -O3 -pipe -march=native   -c -o mdoc_markdown.o mdoc_markdown.c
cc -O3 -pipe -march=native   -c -o out.o out.c
cc -O3 -pipe -march=native   -c -o tag.o tag.c
cc -O3 -pipe -march=native   -c -o tree.o tree.c
cc -O3 -pipe -march=native   -c -o compat_err.o compat_err.c
cc -O3 -pipe -march=native   -c -o compat_fts.o compat_fts.c
cc -O3 -pipe -march=native   -c -o compat_getline.o compat_getline.c
cc -O3 -pipe -march=native   -c -o compat_getsubopt.o compat_getsubopt.c
cc -O3 -pipe -march=native   -c -o compat_isblank.o compat_isblank.c
cc -O3 -pipe -march=native   -c -o compat_mkdtemp.o compat_mkdtemp.c
cc -O3 -pipe -march=native   -c -o compat_ohash.o compat_ohash.c
cc -O3 -pipe -march=native   -c -o compat_progname.o compat_progname.c
cc -O3 -pipe -march=native   -c -o compat_reallocarray.o compat_reallocarray.c
cc -O3 -pipe -march=native   -c -o compat_recallocarray.o compat_recallocarray.c
cc -O3 -pipe -march=native   -c -o compat_strcasestr.o compat_strcasestr.c
cc -O3 -pipe -march=native   -c -o compat_strlcat.o compat_strlcat.c
cc -O3 -pipe -march=native   -c -o compat_strlcpy.o compat_strlcpy.c
cc -O3 -pipe -march=native   -c -o compat_strndup.o compat_strndup.c
cc -O3 -pipe -march=native   -c -o compat_strsep.o compat_strsep.c
cc -O3 -pipe -march=native   -c -o compat_strtonum.o compat_strtonum.c
cc -O3 -pipe -march=native   -c -o compat_vasprintf.o compat_vasprintf.c
cc -O3 -pipe -march=native   -c -o man.o man.c
cc -O3 -pipe -march=native   -c -o man_macro.o man_macro.c
cc -O3 -pipe -march=native   -c -o man_validate.o man_validate.c
cc -O3 -pipe -march=native   -c -o att.o att.c
cc -O3 -pipe -march=native   -c -o lib.o lib.c
cc -O3 -pipe -march=native   -c -o mdoc.o mdoc.c
cc -O3 -pipe -march=native   -c -o mdoc_argv.o mdoc_argv.c
cc -O3 -pipe -march=native   -c -o mdoc_macro.o mdoc_macro.c
cc -O3 -pipe -march=native   -c -o mdoc_state.o mdoc_state.c
cc -O3 -pipe -march=native   -c -o mdoc_validate.o mdoc_validate.c
cc -O3 -pipe -march=native   -c -o st.o st.c
cc -O3 -pipe -march=native   -c -o eqn.o eqn.c
cc -O3 -pipe -march=native   -c -o roff.o roff.c
cc -O3 -pipe -march=native   -c -o roff_validate.o roff_validate.c
cc -O3 -pipe -march=native   -c -o tbl.o tbl.c
cc -O3 -pipe -march=native   -c -o tbl_data.o tbl_data.c
cc -O3 -pipe -march=native   -c -o tbl_layout.o tbl_layout.c
cc -O3 -pipe -march=native   -c -o tbl_opts.o tbl_opts.c
cc -O3 -pipe -march=native   -c -o arch.o arch.c
cc -O3 -pipe -march=native   -c -o chars.o chars.c
cc -O3 -pipe -march=native   -c -o mandoc.o mandoc.c
cc -O3 -pipe -march=native   -c -o mandoc_aux.o mandoc_aux.c
cc -O3 -pipe -march=native   -c -o mandoc_msg.o mandoc_msg.c
cc -O3 -pipe -march=native   -c -o mandoc_ohash.o mandoc_ohash.c
cc -O3 -pipe -march=native   -c -o mandoc_xr.o mandoc_xr.c
cc -O3 -pipe -march=native   -c -o msec.o msec.c
cc -O3 -pipe -march=native   -c -o preconv.o preconv.c
cc -O3 -pipe -march=native   -c -o read.o read.c
cc -O3 -pipe -march=native   -c -o demandoc.o demandoc.c
cc -O3 -pipe -march=native   -c -o soelim.o soelim.c
cc -O3 -pipe -march=native   -c -o compat_stringlist.o compat_stringlist.c
cc -o soelim  soelim.o compat_err.o compat_getline.o compat_progname.o compat_reallocarray.o compat_stringlist.o
/usr/bin/ld: compat_reallocarray.o:(.bss+0x0): multiple definition of `dummy'; compat_getline.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:533: soelim] Error 1
make: *** Waiting for unfinished jobs....
-> mandoc Build failed
```

After the fix this doesn't happen and the build happens fine.

**Comment by git-bruh** [comment]
That's weird... I changed my `CFLAGS` to the ones in your log `-O3 -pipe -march=native` but it still builds fine for me. I've modified the `sed` call in the repo now, because [arch does it](https://github.com/archlinux/svntogit-community/blob/packages/mandoc/trunk/PKGBUILD#L43) for all `compat_*.c` files, should work now.

**Comment by git-bruh** [comment]
Ah sorry my bad, didn't notice that I was using the mandoc build from gkiss repo which already had an extra sed call, hence the build wasn't failing.

**Comment by ominitay** [comment]
No problem! Thanks for fixing it.

**Pull request closed without merging**
