### PR TITLE
firefox[no-gtk2.patch]: fix wayland and syntax errors

### PR DESCRIPTION
**Pull request by git-bruh**
Got messed up [here](https://github.com/kiss-community/repo-main/blob/7fa208cadf0ac7433b61853c4a118af840a7f29b/extra/firefox/patches/no-gtk2.patch#L1235) due to me not being very knowledgable at that time, was manually applying the patch instead of looking at `*.rej`.

### CODE REVIEW

**Comment by dilyn-corner** [comment]
I'm assuming that you've tested this and it builds fine? XD

**Comment by git-bruh** [comment]
It SHOULD build fine (Can't test, only fails with wayland enabled) because someone modified the patch on IRC with the changes i suggested and it worked. The `diff` on `GLContextProviderWayland.cpp` is empty when comparing after applying this patch, and the one [posted on IRC](https://freenode.logbot.info/kisslinux/20210225#c7042358).

**Comment by dilyn-corner** [comment]
If anyone has any issues building `firefox`, I'm almost certain we'll hear about it. 

I really hope that doesn't happen.

**Comment by dilyn-corner** [comment]
30 hours later I can confirm that this patch does result in a `firefox` which builds. Can neither confirm nor deny that it runs. :)

**Pull request merged**
