### PR TITLE
Switch to muon

### PR DESCRIPTION
**Pull request by illiliti**
- [x] ~~atk~~ #67
- [x] foot
- [x] foot-pgo
- [x] freetype-harfbuzz
- [x] gdk-pixbuf
- [x] glib
- [x] grim
- [x] gtk+3
- [x] intel-vaapi-driver
- [x] libdrm
- [x] libinput
- [x] libseat
- [x] libva
- [x] libva-utils
- [x] libxkbcommon
- [ ] mesa
- [x] muon
- [x] mpv
- [x] pango
- [x] slurp
- [x] sway
- [x] sway-no-seat
- [x] sway-tiny
- [x] wayland
- [x] wayland-protocols
- [x] wbg
- [x] ~~wl-clipboard~~ #62
- [x] wlroots
- [x] wlsunset
- [x] xkeyboard-config
- [x] cairo

### CODE REVIEW

**Comment by sewnie** [comment]
What's the benefit of using muon?

**Comment by dilyn-corner** [comment]
You wouldn't need Python as much is a big one. 

Aug 2, 2022, 10:26 AM by ***@***.***:

**Comment by sewnie** [comment]
Wow. Impressive.

I will actually use it in some of my repositories, thank you!

**Comment by illiliti** [comment]
As Dilyn said, it opens an opportunity to get rid of python from the system, however, some effort would still be needed to achieve that.

Another notable advantage is that it is 100x faster and more portable since it can be built using tcc or cproc with no issues.

**Comment by ioraff** [comment]
> I will actually use it in some of my repositories, thank you!

Know that it isn't 100% compatible with meson. For instance, typing in python allowed a lot of meson builds to, for instance, use bools and ints somewhat interchangeably, despite not actually adhering to the meson spec.

**Comment by eli-schwartz** [comment]
Speaking with my Meson dev hat on, I intend to break those projects anyway... Meson should be adhering to its own spec, type violations are a bug that we should be validating.

**Comment by TAAPArthur** [comment]
@illiliti Think it is worth just submitting what you have done and doing the last 2 packages later?

**Comment by illiliti** [comment]
Regarding those last two packages.

muon should be able to build foot-pgo. ioraff submitted a patch which should help it.

As of mesa, it builds fine without llvm support. To build it with llvm, we need to either [add pkgconfig file to llvm](https://github.com/llvm/llvm-project/issues/9777) or implement config-tool to muon. I prefer the former.

So, to merge this PR, first we need to deal with llvm, fix some minor bugs in muon and do full rebuild of the repo. Merging it right now doesn't make sense since i'm not 100% sure that muon is bug-free for our use case. Actually that's why full rebuild is needed - to be sure. I plan to do that soon, just don't have enough time right now.

When this gets merged, i'm open to maintain these packages due to high probability of constant breakages(see glib for example)

**Comment by TAAPArthur** [comment]
Just don't see why it all has to be done at once. I imagine you don't want to do a full rebuild twice, but you only need to rebuild the dependent packages so the work still seems able to be split up.

> bug-free for our use case

Don't know what "our use case" is. Is that building with musl + gcc with unmodified packages? I was expecting things to break and would think that having more testers would help kill all the bugs faster.

**Comment by eli-schwartz** [comment]
I quite agree, you can start off by merging a muon package and transitioning other packages that are known to work correctly. Ship both Meson and muon for a while, that's still more than sufficient to knock python out of the build graph for many packages. Iterate and expand the scope later.

**Comment by illiliti** [comment]
> Just don't see why it all has to be done at once.

Because it's pointless to have both meson and muon in repo. And as i said before, i want to fix muon bugs as much as possible before merging. Doing it at once is a good sign that most bugs are fixed.

> Don't know what "our use case" is. Is that building with musl + gcc with unmodified packages?

Building this repo(+ maybe some essential packages in community) with muon

> I was expecting things to break and would think that having more testers would help kill all the bugs faster.

Nothing stop testers to test packages right now.

> you can start off by merging a muon package and transitioning other packages that are known to work correctly

That's the point, I don't know. I still uncover regressions and hidden bugs to this day in packages that seemingly work "correctly" before.

And i don't understand why we need to hurry with this. We'll always have a time to break everything, give me a chance to reduce that possibility.

> Ship both Meson and muon for a while

master branch represent final state, it should only have either meson or muon. If you need muon+meson combination, you can use this branch already.

**Comment by TAAPArthur** [comment]
>Because it's pointless to have both meson and muon in repo

Not really. We could have multiple build systems. Having meson around doesn't hurt anyone and especially who forked the packages in question and therefore won't be getting the update immediately.

>Building this repo(+ maybe some essential packages in community) with muon

Probably should specify the compiler and if you are building statically or not.

>Nothing stop testers to test packages right now.

Nothing besides cluttering this issue. Would seem more practical to open an issue per package rather than having then all be under this issue. Also "forcing" everyone to test would take more signal than just having volunteers. Similar principle to updating versions/ build scripts without going through rigorous testing. This could be viable if there were some packages that we can't find fault in.

> I still uncover regressions and hidden bugs to this day in packages that seemingly work "correctly" before.

Bugs like what? The package won't build? won't run? won't link? Would help with testing if we knew what to expect/what you already overcame.

>And i don't understand why we need to hurry with this

This issue was created 4mo ago. I didn't think we were in a hurry.

>master branch represent final state, it should only have either meson or muon.

Personally despise this philosophy. Reminds me of the whole x -> wayland move. Sure have this repro suddenly change its preferred packages but why remove the competition? muon and meson aren't 100% compatible and there's no indication that will change. All that decision does is make it marginally harder for someone to use meson which would just be more annoying if something broke (or breaks in the future) relating to muon. It is just like how we can have multiple compilers or wm without religiously picking a favorite for everything even if the default patches/build scripts implicitly favor one over the others

**Comment by eli-schwartz** [comment]
Muon is quite likely to never fully replace Meson, simply because it's a moving target, people will tend to use brand new features of Meson, and specifically because of:
- modules
- languages

Muon supports C/C++/ObjC, but does not support rust, vala, cython, fortran, ObjC++, java, swift, D, cuda, C#...

Muon also doesn't have Meson's specialized Qt module support, cmake support, the python module (beyond a stub) which is seeing some interest in the python community as a setuptools replacement...

All this stuff is a big investment, a huge time sink, and *really* fiddly to get right. Maybe it will eventually happen, maybe not, but there's no question that at least for now, there's lots of reasons users might wish to have Meson installed.

Since you mention Mesa -- one of the Mesa developers is also a Meson developer and has been working on rust support. Future versions of Meson will likely be able to build rust crates as subprojects without cargo, and this is urgently desired by Mesa.


What Muon is, is an excellent tool for covering the common cases, which can generally work unless you have some fairly specialized needs. That's fantastic, and it's great to be able to use it wherever possible.

**Comment by illiliti** [comment]
@TAAPArthur I don't know why you are pressuring me. You want to use muon, you can do it. No need force me to merge WIP stuff. 

> Not really. We could have multiple build systems. 

No, we can't. By the same reason we don't have udev, xorg and stuff...

> Having meson around doesn't hurt anyone and especially who forked the packages in question and therefore won't be getting the update immediately.

Update? You can symlink `version` and `sources` to original package and get updates.

> Would seem more practical to open an issue per package rather than having then all be under this issue

Feel free to report issues directly to muon. 

> Also "forcing" everyone to test would take more signal than just having volunteers.

Not everyone wants to be forced. Some just wants working system.

> Bugs like what? The package won't build? won't run? won't link? Would help with testing if we knew what to expect/what you already overcame.

It depends. Some packages have corrupted pkg-config file. Some compiles but don't link. Some don't install necessary files due to bugs in muon. Full rebuild is a best way to find out.

> Personally despise this philosophy

this isn't about philosophy. this is established practice

> Sure have this repro suddenly change its preferred packages but why remove the competition?

because competition sucks

> muon and meson aren't 100% compatible and there's no indication that will change

there were some talks regarding unified cli.

> All that decision does is make it marginally harder for someone to use meson which would just be more annoying if something broke (or breaks in the future) relating to muon.

That's why this PR is still WIP. I'm working to ensure that breaks will be minimum

> religiously picking a favorite

muon is just better than meson. i'm not picking it for religious reasons. it's just better for various reasons. [Including those you are personally interested in](https://github.com/mesonbuild/meson/pull/8692)




> Muon is quite likely to never fully replace Meson

It will if you stop demotivating me

> simply because it's a moving target

I'll deal with this. If needed, in violent way

> but does not support rust, vala, cython, fortran, ObjC++, java, swift, D, cuda, C#...
> Muon also doesn't have Meson's specialized Qt module support, cmake support, the python module (beyond a stub) which is seeing some interest in the python community as a setuptools replacement...

we don't and will never use this crap

> there's lots of reasons users might wish to have Meson installed.

Nobody and nothing prevent you to keep meson installed. You're trying to apply your "generic" distro expertise, please be aware it doesn't work here. Our users have freedom of choice. Everyone can switch everything, there's absolutely no lock-in. This repo just have sane defaults, that's all. We don't dictate them in any way. We are not dictators unlike those "generic" distros.

**Comment by TAAPArthur** [comment]
>@TAAPArthur I don't know why you are pressuring me.

Was just asking questions and responding to your comments.

>>  Not really. We could have multiple build systems.
> No, we can't. By the same reason we don't have udev, xorg and stuff...

I mean we can but just choose not to. Just like we have gcc/tcc/clang.

>Update? You can symlink version and sources to original package and get updates.

Suppose I forked package X that used meson. You remove meson from the repo. I now may not be able to build my program because the meson package from this repo has been removed. 
Not saying this is catastrophic, but I'd count it as a negative with no upside compared to just leaving meson alone. 

>Not everyone wants to be forced. Some just wants working system.

Sounds ideal, but not inline with this practices of this repo. Some people are gonna be unhappy; we can just choose which.

>there were some talks regarding unified cli.

cli compatibility is still listed as a non-feature of muon.

>That's why this PR is still WIP. I'm working to ensure that breaks will be minimum

minimum number of breaks is 0. Not saying you can't achieve that just questioning how much is worth it.

>muon is just better than meson. i'm not picking it for religious reasons. it's just better for various reasons. 

I mean there is a reason I'm in favor of this PR. But just because we think it is better, I don't imagine it replacing meson. If package X keeps wanting to use the latest feature of meson and therefore breaks every release with muon, can easily see people just preferring the stability. Believe @eli-schwartz mentioned a whole list of features meson has that muon doesn't. And meson's worth really increases when you are trying to build that special program that uses all these "features". 
My point is that "better" isn't determined by the design but by if it works for the relevant usecases which will vary per person.

>It will if you stop demotivating me

Not according to the muon's home page. Also I can't control your motivation, but I'm basically saying I like the work you've done and wish for it to be merge sooner.

>we don't and will never use this crap

except for all the places we do. The "official" repos have cmake at the very least which is arguably worse than meson

>Our users have freedom of choice.

So do users of every open platform. But there's something to be said about not reduplicating work and preventing unneeded conflict. The argument for keeping meson is that removing helps none and hurts some people and keeping it hurts no one. 

>We are not dictators unlike those "generic" distros.

Doesn't our BDFL have a tendency to disappear and comeback and enforce drastic changes to our packing style? And doesn't he have final say on everything?

----------------------

Ignoring the philosophy and getting back on topic, it seems we could either
1. Let @illiliti keep working at his own pace
2. Fork what he's already done and start the gradual conversion process.  
3. Have a special muon repo that has only the packages we currently think work. And when we are confident everything works, then try to merge it.
4. All work independently on the same problem and duplicate work

I'm voting for option 2

**Comment by sewnie** [comment]
guys i dont think asking the benefits of muon was a good idea to say

**Comment by dilyn-corner** [comment]
2 is just using this PR's branch. 

Just leave it. There's no good reason to have muon and meson available because one is a less feature complete version of the other.

**Pull request closed without merging**
